### ISSUE TITLE
Why only few pokemons available in base category?

### ISSUE THREAD

**Issue by chinchang** [rstacruz/weedlecalc.com#1]
Eg. Meowth is not there in base category.

**Comment by corroded** [comment]
I would assume because they're either very common pokemon (i.e. rattata, zubat) and/or they don't require that many candies (i.e. pidgey, caterpie, etc.). Meowths require a lot of candies and they aren't that common either - unless you live near a meowth nest.

**Comment by rstacruz** [comment]
1. I wanted to make it easy to use. You'll probably be evolving your
   throwaway pokemon.
2. I had to enter all that data by hand, I didn't want to spend time
   finding all the candy requirements for 150 pokemon :P

**Comment by chinchang** [comment]
Makes sense :)
